#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
    update-alternatives --install /usr/bin/x-www-browser \
        x-www-browser /opt/Liya/liya 80
    chown root /opt/Liya/chrome-sandbox
    chmod 4755 /opt/Liya/chrome-sandbox
    echo "Run sudo xdg-settings set default-web-browser liya.desktop && sudo update-alternatives --config x-www-browser to set Liya as your default browser."
    ln -sf /opt/Liya/liya /usr/bin/liya
fi
